<a href="https://colab.research.google.com/github/NAMITHASS/SCRATCH/blob/main/numpy_d1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[1,2,3]
b=[2,3,4]
l=a+b
l.append([1,2])
l

[1, 2, 3, 2, 3, 4, [1, 2]]

In [ ]:
a=(1,2,3)
b=(2,3,4)
l=a+b
l

(1, 2, 3, 2, 3, 4)

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a.shape

(7,)

In [ ]:
a=np.array([1,2,3],dtype=np.float64)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a=np.ones(3)
b=np.zeros(3)
c=np.random.random(3)
print(a)
print(b)
print(c)

[1. 1. 1.]
[0. 0. 0.]
[0.0315758  0.67718973 0.89361632]


In [ ]:
a=np.ones((4,3,2))
b=np.zeros((4,3,2))
c=np.random.random((4,3,2))
print(a,b,c)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]] [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] [[[0.67911628 0.35088464]
  [0.50226194 0.38160338]
  [0.70998784 0.2294096 ]]

 [[0.60272745 0.0057218 ]
  [0.79662363 0.74808235]
  [0.86705116 0.71674309]]

 [[0.67344741 0.96629358]
  [0.82050892 0.03382748]
  [0.60797929 0.104127  ]]

 [[0.74531128 0.63395662]
  [0.88655576 0.3029274 ]
  [0.21766715 0.08778115]]]


In [ ]:
d=np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f=np.arange(10,50,5)
print(f)

[10 15 20 25 30 35 40 45]


In [ ]:
c=np.full((2,2),7) #constant
print(c)

[[7 7]
 [7 7]]


In [ ]:
g=np.linspace(0.,1.,num=5)
print(g)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
a=np.array([[1,2,3,4],[1,5,6,7],[4,7,6,3]])
print(a[0:2,0])
c=a.shape
print(c)
b=a[1:3,2:4]
print(b)

[1 1]
(3, 4)
[[6 7]
 [6 3]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,9],[2,4,1,2]])
print(a)

[[1 2 3 4]
 [5 6 7 9]
 [2 4 1 2]]


In [ ]:
r1=a[1,:]
r2=a[1:2,:]
r3=a[[1],:]
print(r1,r1.shape)
print(r2,r2.shape)
print(r2,r3.shape)

[5 6 7 9] (4,)
[[5 6 7 9]] (1, 4)
[[5 6 7 9]] (1, 4)


In [ ]:
c1=a[:,1]
c2=a[:,1:2]
print(c1,c1.shape)
print(c2,c2.shape)

[2 6 4] (3,)
[[2]
 [6]
 [4]] (3, 1)
